package com.mouserecorder.wrappers;

import com.github.kwhat.jnativehook.keyboard.NativeKeyEvent;

import java.awt.event.KeyEvent;
import java.util.HashMap;
import java.util.Map;

public class NativeWrapper {
    private static final Map<Integer, Integer> keyCodesDictionary = new HashMap<>();

    static {
        keyCodesDictionary.put(NativeKeyEvent.VC_ESCAPE, KeyEvent.VK_ESCAPE);
        keyCodesDictionary.put(NativeKeyEvent.VC_F1, KeyEvent.VK_F1);
        keyCodesDictionary.put(NativeKeyEvent.VC_F2, KeyEvent.VK_F2);
        keyCodesDictionary.put(NativeKeyEvent.VC_F3, KeyEvent.VK_F3);
        keyCodesDictionary.put(NativeKeyEvent.VC_F4, KeyEvent.VK_F4);
        keyCodesDictionary.put(NativeKeyEvent.VC_F5, KeyEvent.VK_F5);
        keyCodesDictionary.put(NativeKeyEvent.VC_F6, KeyEvent.VK_F6);
        keyCodesDictionary.put(NativeKeyEvent.VC_F7, KeyEvent.VK_F7);
        keyCodesDictionary.put(NativeKeyEvent.VC_F8, KeyEvent.VK_F8);
        keyCodesDictionary.put(NativeKeyEvent.VC_F9, KeyEvent.VK_F9);
        keyCodesDictionary.put(NativeKeyEvent.VC_F10, KeyEvent.VK_F10);
        keyCodesDictionary.put(NativeKeyEvent.VC_F11, KeyEvent.VK_F11);
        keyCodesDictionary.put(NativeKeyEvent.VC_F12, KeyEvent.VK_F12);
        keyCodesDictionary.put(NativeKeyEvent.VC_F13, KeyEvent.VK_F13);
        keyCodesDictionary.put(NativeKeyEvent.VC_F14, KeyEvent.VK_F14);
        keyCodesDictionary.put(NativeKeyEvent.VC_F15, KeyEvent.VK_F15);
        keyCodesDictionary.put(NativeKeyEvent.VC_F16, KeyEvent.VK_F16);
        keyCodesDictionary.put(NativeKeyEvent.VC_F17, KeyEvent.VK_F17);
        keyCodesDictionary.put(NativeKeyEvent.VC_F18, KeyEvent.VK_F18);
        keyCodesDictionary.put(NativeKeyEvent.VC_F19, KeyEvent.VK_F19);
        keyCodesDictionary.put(NativeKeyEvent.VC_F20, KeyEvent.VK_F20);
        keyCodesDictionary.put(NativeKeyEvent.VC_F21, KeyEvent.VK_F21);
        keyCodesDictionary.put(NativeKeyEvent.VC_F22, KeyEvent.VK_F22);
        keyCodesDictionary.put(NativeKeyEvent.VC_F23, KeyEvent.VK_F23);
        keyCodesDictionary.put(NativeKeyEvent.VC_F24, KeyEvent.VK_F24);
        keyCodesDictionary.put(NativeKeyEvent.VC_BACKQUOTE, KeyEvent.VK_BACK_QUOTE);
        keyCodesDictionary.put(NativeKeyEvent.VC_1, KeyEvent.VK_NUMPAD1);
        keyCodesDictionary.put(NativeKeyEvent.VC_2, KeyEvent.VK_NUMPAD2);
        keyCodesDictionary.put(NativeKeyEvent.VC_3, KeyEvent.VK_NUMPAD3);
        keyCodesDictionary.put(NativeKeyEvent.VC_4, KeyEvent.VK_NUMPAD4);
        keyCodesDictionary.put(NativeKeyEvent.VC_5, KeyEvent.VK_NUMPAD5);
        keyCodesDictionary.put(NativeKeyEvent.VC_6, KeyEvent.VK_NUMPAD6);
        keyCodesDictionary.put(NativeKeyEvent.VC_7, KeyEvent.VK_NUMPAD7);
        keyCodesDictionary.put(NativeKeyEvent.VC_8, KeyEvent.VK_NUMPAD8);
        keyCodesDictionary.put(NativeKeyEvent.VC_9, KeyEvent.VK_NUMPAD9);
        keyCodesDictionary.put(NativeKeyEvent.VC_0, KeyEvent.VK_NUMPAD0);
        keyCodesDictionary.put(NativeKeyEvent.VC_MINUS, KeyEvent.VK_MINUS);
        keyCodesDictionary.put(NativeKeyEvent.VC_EQUALS, KeyEvent.VK_EQUALS);
        keyCodesDictionary.put(NativeKeyEvent.VC_BACKSPACE, KeyEvent.VK_BACK_SPACE);
        keyCodesDictionary.put(NativeKeyEvent.VC_TAB, KeyEvent.VK_TAB);
        keyCodesDictionary.put(NativeKeyEvent.VC_CAPS_LOCK, KeyEvent.VK_CAPS_LOCK);
        keyCodesDictionary.put(NativeKeyEvent.VC_A, KeyEvent.VK_A);
        keyCodesDictionary.put(NativeKeyEvent.VC_B, KeyEvent.VK_B);
        keyCodesDictionary.put(NativeKeyEvent.VC_C, KeyEvent.VK_C);
        keyCodesDictionary.put(NativeKeyEvent.VC_D, KeyEvent.VK_D);
        keyCodesDictionary.put(NativeKeyEvent.VC_E, KeyEvent.VK_E);
        keyCodesDictionary.put(NativeKeyEvent.VC_F, KeyEvent.VK_F);
        keyCodesDictionary.put(NativeKeyEvent.VC_G, KeyEvent.VK_G);
        keyCodesDictionary.put(NativeKeyEvent.VC_H, KeyEvent.VK_H);
        keyCodesDictionary.put(NativeKeyEvent.VC_I, KeyEvent.VK_I);
        keyCodesDictionary.put(NativeKeyEvent.VC_J, KeyEvent.VK_J);
        keyCodesDictionary.put(NativeKeyEvent.VC_K, KeyEvent.VK_K);
        keyCodesDictionary.put(NativeKeyEvent.VC_L, KeyEvent.VK_L);
        keyCodesDictionary.put(NativeKeyEvent.VC_M, KeyEvent.VK_M);
        keyCodesDictionary.put(NativeKeyEvent.VC_N, KeyEvent.VK_N);
        keyCodesDictionary.put(NativeKeyEvent.VC_O, KeyEvent.VK_O);
        keyCodesDictionary.put(NativeKeyEvent.VC_P, KeyEvent.VK_P);
        keyCodesDictionary.put(NativeKeyEvent.VC_Q, KeyEvent.VK_Q);
        keyCodesDictionary.put(NativeKeyEvent.VC_R, KeyEvent.VK_R);
        keyCodesDictionary.put(NativeKeyEvent.VC_S, KeyEvent.VK_S);
        keyCodesDictionary.put(NativeKeyEvent.VC_T, KeyEvent.VK_T);
        keyCodesDictionary.put(NativeKeyEvent.VC_U, KeyEvent.VK_U);
        keyCodesDictionary.put(NativeKeyEvent.VC_V, KeyEvent.VK_V);
        keyCodesDictionary.put(NativeKeyEvent.VC_W, KeyEvent.VK_W);
        keyCodesDictionary.put(NativeKeyEvent.VC_X, KeyEvent.VK_X);
        keyCodesDictionary.put(NativeKeyEvent.VC_Y, KeyEvent.VK_Y);
        keyCodesDictionary.put(NativeKeyEvent.VC_Z, KeyEvent.VK_Z);
        keyCodesDictionary.put(NativeKeyEvent.VC_OPEN_BRACKET, KeyEvent.VK_OPEN_BRACKET);
        keyCodesDictionary.put(NativeKeyEvent.VC_CLOSE_BRACKET, KeyEvent.VK_CLOSE_BRACKET);
        keyCodesDictionary.put(NativeKeyEvent.VC_BACK_SLASH, KeyEvent.VK_BACK_SLASH);
        keyCodesDictionary.put(NativeKeyEvent.VC_SEMICOLON, KeyEvent.VK_SEMICOLON);
        keyCodesDictionary.put(NativeKeyEvent.VC_QUOTE, KeyEvent.VK_QUOTE);
        keyCodesDictionary.put(NativeKeyEvent.VC_ENTER, KeyEvent.VK_ENTER);
        keyCodesDictionary.put(NativeKeyEvent.VC_COMMA, KeyEvent.VK_COMMA);
        keyCodesDictionary.put(NativeKeyEvent.VC_PERIOD, KeyEvent.VK_PERIOD);
        keyCodesDictionary.put(NativeKeyEvent.VC_SLASH, KeyEvent.VK_SLASH);
        keyCodesDictionary.put(NativeKeyEvent.VC_SPACE, KeyEvent.VK_SPACE);
        keyCodesDictionary.put(NativeKeyEvent.VC_PRINTSCREEN, KeyEvent.VK_PRINTSCREEN);
        keyCodesDictionary.put(NativeKeyEvent.VC_SCROLL_LOCK, KeyEvent.VK_SCROLL_LOCK);
        keyCodesDictionary.put(NativeKeyEvent.VC_PAUSE, KeyEvent.VK_PAUSE);
        keyCodesDictionary.put(NativeKeyEvent.VC_INSERT, KeyEvent.VK_INSERT);
        keyCodesDictionary.put(NativeKeyEvent.VC_DELETE, KeyEvent.VK_DELETE);
        keyCodesDictionary.put(NativeKeyEvent.VC_HOME, KeyEvent.VK_HOME);
        keyCodesDictionary.put(NativeKeyEvent.VC_END, KeyEvent.VK_END);
        keyCodesDictionary.put(NativeKeyEvent.VC_PAGE_UP, KeyEvent.VK_PAGE_UP);
        keyCodesDictionary.put(NativeKeyEvent.VC_PAGE_DOWN, KeyEvent.VK_PAGE_DOWN);
        keyCodesDictionary.put(NativeKeyEvent.VC_UP, KeyEvent.VK_UP);
        keyCodesDictionary.put(NativeKeyEvent.VC_LEFT, KeyEvent.VK_LEFT);
        keyCodesDictionary.put(NativeKeyEvent.VC_CLEAR, KeyEvent.VK_CLEAR);
        keyCodesDictionary.put(NativeKeyEvent.VC_RIGHT, KeyEvent.VK_RIGHT);
        keyCodesDictionary.put(NativeKeyEvent.VC_DOWN, KeyEvent.VK_DOWN);
        keyCodesDictionary.put(NativeKeyEvent.VC_NUM_LOCK, KeyEvent.VK_NUM_LOCK);
        keyCodesDictionary.put(NativeKeyEvent.VC_SEPARATOR, KeyEvent.VK_SEPARATOR);
        keyCodesDictionary.put(NativeKeyEvent.VC_SHIFT, KeyEvent.VK_SHIFT);
        keyCodesDictionary.put(3638, KeyEvent.VK_SHIFT);
        keyCodesDictionary.put(NativeKeyEvent.VC_CONTROL, KeyEvent.VK_CONTROL);
        keyCodesDictionary.put(NativeKeyEvent.VC_ALT, KeyEvent.VK_ALT);
        keyCodesDictionary.put(NativeKeyEvent.VC_META, KeyEvent.VK_WINDOWS);
        keyCodesDictionary.put(NativeKeyEvent.VC_CONTEXT_MENU, KeyEvent.VK_CONTEXT_MENU);
        keyCodesDictionary.put(NativeKeyEvent.VC_KATAKANA, KeyEvent.VK_KATAKANA);
        keyCodesDictionary.put(NativeKeyEvent.VC_UNDERSCORE, KeyEvent.VK_UNDERSCORE);
        keyCodesDictionary.put(NativeKeyEvent.VC_KANJI, KeyEvent.VK_KANJI);
        keyCodesDictionary.put(NativeKeyEvent.VC_HIRAGANA, KeyEvent.VK_HIRAGANA);
        keyCodesDictionary.put(NativeKeyEvent.VC_SUN_HELP, KeyEvent.VK_HELP);
        keyCodesDictionary.put(NativeKeyEvent.VC_SUN_STOP, KeyEvent.VK_STOP);
        keyCodesDictionary.put(NativeKeyEvent.VC_SUN_PROPS, KeyEvent.VK_PROPS);
        keyCodesDictionary.put(NativeKeyEvent.VC_SUN_FIND, KeyEvent.VK_FIND);
        keyCodesDictionary.put(NativeKeyEvent.VC_SUN_AGAIN, KeyEvent.VK_AGAIN);
        keyCodesDictionary.put(NativeKeyEvent.VC_SUN_COPY, KeyEvent.VK_COPY);
        keyCodesDictionary.put(NativeKeyEvent.VC_SUN_CUT, KeyEvent.VK_CUT);
    }

    // 将原生键码映射到虚拟键码
    public static int mapNativeKey(int nativeKeyCode) {
        return keyCodesDictionary.getOrDefault(nativeKeyCode, KeyEvent.VK_UNDEFINED);
    }
}
